<?php
$selCurrency = $info->currency>0?$info->currency:1;
?>

<h5><?=$info->text?></h5>


<div class="form-row">
    <div class="form-group col-md-5">
        <input type="text" class="form-control <?=$info->jsMask?> <?=$info->hasError?'is-invalid':''?>" name="<?=$inGroup?"info[{$info->extId}][amount]":'data[amount]'?>" placeholder="<?=htmlspecialchars($info->placeholder)?>" value="<?=$info->amountText?>">
        <div class="invalid-feedback"><?=$info->errorMessage?></div>
    </div>
    <div class="form-group col-md-3">
        <select class="form-control" name="<?=$inGroup?"info[{$info->extId}][currency]":'data[currency]'?>">
            <?php foreach ($info->currencies as $key=>$currency): ?>
                <option value="<?=$key?>" <?=$selCurrency==$key?'selected':''?>><?=$currency['name']?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>

<?php if (!$inGroup): ?>
<div class="mt-1">
    <?php require __DIR__.'/button-group.php'; ?>
</div>
<input type="hidden" name="info_id" value="<?=$info->extId?>">
<?php endif; ?>