<?php
$selUnit = $info->dataUnit>0?$info->dataUnit:1;
?>
<h5><?=$info->text?></h5>

<div class="form-row">
    <div class="form-group col-md-5">
        <input type="text" class="form-control <?=$info->hasError?'is-invalid':''?>" id="info<?=$info->extId?>" name="<?=$inGroup?"info[{$info->extId}][amount]":'data[amount]'?>" placeholder="<?=htmlspecialchars($info->placeholder)?>" value="<?=$info->amountText?>" >
        <div class="invalid-feedback"><?=$info->errorMessage?></div>
    </div>
    <div class="form-group col-md-3">
        <select name="<?=$inGroup?"info[{$info->extId}][unit]":'data[unit]'?>" class="form-control">
            <?php foreach($info->units as $key=>$unit): ?>
                <option value="<?=$key?>" <?=$selUnit==$key?'selected':''?>><?=$unit['name']?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>


<?php if (!$inGroup): ?>
<div class="mt-1">
    <?php require __DIR__.'/button-group.php'; ?>
</div>
<input type="hidden" name="info_id" value="<?=$info->extId?>">
<?php endif; ?>