<div class="entity-block">
    <div class="entity-text form-group">
        <label for="info<?=$info->extId?>"><?=$info->text?></label>
        <div class="row date info-datepicker">
            <div class="col input-group ">
                <input type="text" class="form-control <?=$info->hasError?'is-invalid':''?>" autocomplete="off" id="info<?=$info->extId?>" name="<?=$inGroup?"info[{$info->extId}]":'data'?>" value="<?=htmlspecialchars($info->dataText)?>" placeholder="<?=htmlspecialchars($info->placeholder)?>" >
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="button-addon2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="18" viewBox="0 0 14 16" class="octicon"><path fill-rule="evenodd" d="M13 2h-1v1.5c0 .28-.22.5-.5.5h-2c-.28 0-.5-.22-.5-.5V2H6v1.5c0 .28-.22.5-.5.5h-2c-.28 0-.5-.22-.5-.5V2H2c-.55 0-1 .45-1 1v11c0 .55.45 1 1 1h11c.55 0 1-.45 1-1V3c0-.55-.45-1-1-1zm0 12H2V5h11v9zM5 3H4V1h1v2zm6 0h-1V1h1v2zM6 7H5V6h1v1zm2 0H7V6h1v1zm2 0H9V6h1v1zm2 0h-1V6h1v1zM4 9H3V8h1v1zm2 0H5V8h1v1zm2 0H7V8h1v1zm2 0H9V8h1v1zm2 0h-1V8h1v1zm-8 2H3v-1h1v1zm2 0H5v-1h1v1zm2 0H7v-1h1v1zm2 0H9v-1h1v1zm2 0h-1v-1h1v1zm-8 2H3v-1h1v1zm2 0H5v-1h1v1zm2 0H7v-1h1v1zm2 0H9v-1h1v1z"/></svg>
                    </button>
                </div>
                <div class="invalid-feedback"><?=$info->errorMessage?></div>
            </div>
            <div class="col"></div>
        </div>
    </div>

    <p></p>
    <?php if (!$inGroup): ?>
        <?php require __DIR__.'/button-group.php'; ?>
        <input type="hidden" name="info_id" value="<?=$info->extId?>">
    <?php endif; ?>
</div>

<script type="text/javascript">
    $('.info-datepicker').datepicker({
        format: 'dd.mm.yyyy',
        language: 'ru',
        autoclose: true
    })
</script>