<?php
$selCurrency = $info->currency>0?$info->currency:1;
?>

<div class="entity-block">
    <div class="entity-text"><?=$info->text?></div>
    <div class="form-inline row" >
        <div class="form-group col-sm-4 <?=$info->hasError?'has-error':''?>">
            <label class="control-label" >Сумма:</label>
            <input type="text" class="form-control input-sm" id="info<?=$info->extId?>" name="<?=$inGroup?"info[{$info->extId}][amount]":'data[amount]'?>"  placeholder="<?=htmlspecialchars($info->placeholder)?>" value="<?=$info->amountText?>" >
            <?php if ($info->hasError): ?><label class="control-label" for="info<?=$info->extId?>"><?=$info->errorMessage?></label><?php endif; ?>
        </div>
        <div class="form-group col-sm-4">
            <label class="control-label" >Валюта:</label>
            <select class="form-control input-sm" name="<?=$inGroup?"info[{$info->extId}][currency]":'data[currency]'?>">

            <?php foreach ($info->currencies as $key=>$currency): ?>
                <option value="<?=$key?>"  <?=$selCurrency==$key?'selected':''?>><?=$currency['name']?></option>
            <?php endforeach; ?>
            </select>
        </div>
    </div>
    <p></p>
    <?php if (!$inGroup): ?>
        <?php require __DIR__.'/button-group.php'; ?>
        <input type="hidden" name="info_id" value="<?=$info->extId?>">
    <?php endif; ?>
</div>
