<?php
$selPeriod = $info->dataPeriod>0?$info->dataPeriod:1;
?>
<div class="entity-block">
    <div class="entity-text"><?=$info->text?></div>

    <div class="form-inline row">
        <div class="form-group col-sm-4 <?=$info->hasError?'has-error':''?>">
            <label class="control-label" >Срок:</label>
            <input type="text" class="form-control input-sm" id="info<?=$info->extId?>" name="<?=$inGroup?"info[{$info->extId}][amount]":'data[amount]'?>" placeholder="<?=htmlspecialchars($info->placeholder)?>" value="<?=$info->amountText?>" >
            <?php if ($info->hasError): ?><label class="control-label" for="info<?=$info->extId?>"><?=$info->errorMessage?></label><?php endif; ?>
        </div>
        <div class="col-sm-2">
            <select class="form-control input-sm" name="<?=$inGroup?"info[{$info->extId}][period]":'data[period]'?>" >
            <?php foreach ($info->periods as $key=>$period): ?>
                <option value="<?=$key?>" <?=$selPeriod==$key?'selected':''?>><?=$period['name']?></option>
            <?php endforeach; ?>
            </select>
        </div>
    </div>
    <p></p>
    <div>
        <?php if (!$inGroup): ?>
            <?php require __DIR__.'/button-group.php'; ?>
            <input type="hidden" name="info_id" value="<?=$info->extId?>">
        <?php endif; ?>
    </div>
</div>
