<h1>Список элементов</h1>

<form action="/service2/objects_list" method="POST" target="_blank">
    <b>Algorithm Id:</b><input type="text" name="algorithmId">
    <b>Context Id:</b><input type="text" name="contextId">
  <!--  <b>Link Type:</b><input type="text" name="linkType"> -->
    <br>
    <b>Extra context IDS:</b><br>
    <textarea rows="15" cols="50" name="extraContextIds"></textarea>
    <br>
    <b>Answers:</b><br>
    <textarea rows="15" cols="50" name="answers"></textarea>
    <br>
    <br>
    <b>Info Data:</b><br>
    <textarea rows="15" cols="50" name="infoData"></textarea>
    <br>
    <input type="submit" value=">>>">
</form>

