<div class="row-fluid" xmlns="http://www.w3.org/1999/html">
        <div class="span8 offset2">
            <br>
            <h1>Send RSK File</h1>
            <br>
            <form action="/service/put-rsk-file" method="post" target="_blank" enctype="multipart/form-data">

            <input type="file" name="rsk-file">

            <br><br>
            <button class="btn btn-default" type="submit">Отправить</button>
            </form>
        </div>
    </div>
