<div class="row-fluid" xmlns="http://www.w3.org/1999/html">
        <div class="span8 offset2">
            <br>
            <h1>Send RSK File</h1>
            <br>
            <form action="/service/upload-file" method="post" target="_blank" enctype="multipart/form-data">

                fileWebID: <input type="text" name="fileWebID"><br>

                UID: <input type="text" name="UID"><br>

                UID: <input type="text" name="UID"><br>


            <input type="file" name="info-file">

            <br><br>
            <button class="btn btn-default" type="submit">Отправить</button>
            </form>
        </div>
    </div>
