Word Renderer

<ul>
    <li><a href="https://i.ytimg.com/vi/-qgjF9huHX4/maxresdefault.jpg" target="_blank">https://i.ytimg.com/vi/-qgjF9huHX4/maxresdefault.jpg</a></li>
    <li><a href="https://avatars.mds.yandex.net/get-zen_doc/1136050/pub_5cf154c6e84caf00ae7aa14f_5cf15a96db8c7100afb2ff49/scale_1200" target="_blank">https://avatars.mds.yandex.net/get-zen_doc/1136050/pub_5cf154c6e84caf00ae7aa14f_5cf15a96db8c7100afb2ff49/scale_1200</a></li>
    <li><a href="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSX_bq38Rq-TZucXeiBu1-nU86Uph4ASOrANW5TFIKlNP2yF3Ns&usqp=CAU" target="_blank">https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSX_bq38Rq-TZucXeiBu1-nU86Uph4ASOrANW5TFIKlNP2yF3Ns&usqp=CAU</a></li>
</ul>

<form action="/test/word-renderer-file" method="post" target="_blank">
    Image 1: <input type="text" name="url_1"><br>
    Image 2: <input type="text" name="url_2"><br>
    <button type="submit">Отправить</button>
</form>