<?php
/** @var  Model\Question\Common $question */
$selAnswerId = $question->getSelectedAnswerId();
?>
<?php if($question->listView): ?>
<div class="entity-block">
    <div class="entity-text"><?=$question->text?></div>
    <div>
        <br>
        <select class="form-control js-select" autocomplete="off" id="qst-ans-block-<?=$question->extId?>" name="answer_id">
            <?php $i=0; foreach ($question->answers as $answer): ?>
                <option value="<?=$answer->id?>" <?=$answer->id==$selAnswerId?'selected':''?> ><?=$answer->text?></option>
            <?php $i++; endforeach; ?>
        </select>
        <br>
    </div>
    <div>
        <?php if (!$question->isEmpty('answerId')): ?>
            <button  type="submit" class="btn btn-sm btn-default" id="qst-chg-btn-<?=$question->extId?>">Изменить</button>
        <?php else: ?>
            <button  type="submit" class="btn btn-sm btn-primary">Ответить</button>
        <?php endif; ?>
    </div>
</div>

<input type="hidden" name="question_id" value="<?=$question->extId?>">

<?php else: ?>
<div class="entity-block">
    <div class="entity-text"><?=$question->text?></div>
    <div id="qst-ans-block-<?=$question->extId?>">
        <?php $i=0; foreach ($question->answers as $answer): ?>

        <label class="radio">
            <input type="radio" name="answer_id" value="<?=$answer->id?>" <?=$answer->id==$selAnswerId?'checked':''?> >
            <?=$answer->text?>
        </label>
        <?php $i++; endforeach; ?>
    </div>
    <div>
        <?php if (!$question->isEmpty('answerId')): ?>
            <button  type="submit" class="btn btn-sm btn-default" id="qst-chg-btn-<?=$question->extId?>">Изменить</button>
        <?php else: ?>
            <button  type="submit" class="btn btn-sm btn-primary">Ответить</button>
        <?php endif; ?>
    </div>
</div>

<input type="hidden" name="question_id" value="<?=$question->extId?>">

<script>
    (function () {
        var chgBtnId = 'qst-chg-btn-<?=$question->extId?>';
        var block = document.getElementById('qst-ans-block-<?=$question->extId?>');
        var isChange = <?=$question->isEmpty('answerId')?'false':'true'?>;

        var inputs = block.getElementsByTagName('input');

        if (!inputs.length>0)
            return;

        var form = inputs[0].form;

        for (var i = 0; i < inputs.length; i++) {
            inputs[i].addEventListener("click", function () {
                if (isChange) {
                    form.submit();

                    for (var i = 0; i < inputs.length; i++)
                        inputs[i].disabled = true;
                }
            });
        }

        if (isChange)
            document.getElementById(chgBtnId).style.display = 'none';
    })();
</script>
<?php endif; ?>