<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv=Content-Type content="text/html; charset=windows-1251"/>
    <title>Riskover API</title>
    <link rel="stylesheet" href="/css/bootstrap.css" type="text/css"/>
    <link rel="stylesheet" href="/css/bootstrap-responsive.css" type="text/css"/>
    <link rel="stylesheet" href="/css/docs.css" type="text/css"/>
</head>
<body style="padding-top: 0px;">
<header id="overview" class="jumbotron subhead">
    <div class="container">
        <h1>Riskover</h1>
        <p class="lead">Экспертные системы</p>
    </div>
</header>


<div class="container">
    <div class="row">
        <div class="span4 offset4" align="center">
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <h1>404</h1>
            <h2>Страница не найдена</h2>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
        </div>
    </div>

</div>
<footer class="footer">
    <div class="container">
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
    </div>
</footer>

</body>
</html>