<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv=Content-Type content="text/html; charset=UTF-8"/>
    <title>Riskover API</title>
    <link rel="stylesheet" href="/css/bootstrap.css" type="text/css"/>
    <link rel="stylesheet" href="/css/bootstrap-responsive.css" type="text/css"/>
    <link rel="stylesheet" href="/css/docs.css" type="text/css"/>
</head>
<body style="padding-top: 0px;">
<header id="overview" class="jumbotron subhead">
    <div class="container">
        <h1>Service</h1>
        <p class="lead">Botman</p>
    </div>
</header>


<div class="container">
    <?=$content?>
</div>

<footer class="footer">
    <div class="container">
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
    </div>
</footer>

</body>
</html>