<!DOCTYPE html>
<html>
<head>
    <meta http-equiv=Content-Type content="text/html; charset=UTF-8"/>

    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="/css/admin.css" />

    <script type="text/javascript" src="/js/jquery-1.8.2.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
</head>
<body>
<div class="row-fluid">
    <div class="span10 offset1"><h1><span>Riskover</span></h1></div>
</div>
<hr>
<br>
<div class="row-fluid">
    <div class="span10 offset1">
    <?=$content?>
    </div>
</div>
</body>
</html>