
    <div class="row">
        <div class="span4 offset4" align="center">
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <form action="/import/run-import" method="post">
            <p><button type="submit" class="btn btn-large btn-primary" style="width: 100%;">Синхронизировать БД</button></p>
            <input type="hidden" name="run-import" value="database">
            </form>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
        </div>
    </div>
